### ISSUE TITLE
Exception when trying to run

### ISSUE THREAD

**Issue by codybunea** [klebervirgilio/quaker3_log_parser#1]
When trying to run based on the readme, I'm getting the following exception.

Unsure if there are any dependencies or environment setup tasks I need to complete prior to running.

```
Codys-MBP:kleber-quaker3_log_parser-master codybunea$ ./bin/q3log -l ~/games.log -f json -o ./out.json
hmm... I coudn't find the /Users/codybunea/games.log. Have you provided the absolute path?
Codys-MBP:kleber-quaker3_log_parser-master codybunea$ ./bin/q3log -l ../quake-logfile-parser/games.log -f json -o ./out.json
/Users/codybunea/Code/kleber-quaker3_log_parser-master/parser/compute_death_stats.rb:4:in `call': undefined method `kill_line?' for ComputeDeathStats:Module (NoMethodError)
	from /Users/codybunea/Code/kleber-quaker3_log_parser-master/parser/parser.rb:12:in `block (2 levels) in perform'
	from /Users/codybunea/Code/kleber-quaker3_log_parser-master/parser/parser.rb:10:in `each_line'
	from /Users/codybunea/Code/kleber-quaker3_log_parser-master/parser/parser.rb:10:in `block in perform'
	from /Users/codybunea/Code/kleber-quaker3_log_parser-master/parser/parser.rb:9:in `tap'
	from /Users/codybunea/Code/kleber-quaker3_log_parser-master/parser/parser.rb:9:in `perform'
	from ./bin/q3log:33:in `<main>'
```

**Comment by codybunea** [comment]
I see this was fixed by commit: b48e0ac170210d9db381590515672377a683c646
